pull gflags.gyp changes from webrtc
gflags has a build warning in the chromium version.

../../third_party/gflags/src/gflags.cc:281:53: error: unused typedef 'true_false_equal' [-Werror,-Wunused-local-typedef]
    COMPILE_ASSERT(sizeof(kTrue) == sizeof(kFalse), true_false_equal);
                                                    ^
1 error generated.
[8/231] CXX obj/chromium/src/testing/gtest/src/gtest.gtest.o

Its been reported and fixed upstream
https://github.com/gflags/gflags/issues/125

But not pulled into chromium.  Last update to flags was in 2013.
This change disables the warning.

R=harryjin@google.com, kjellander@chromium.org, jkellander@chromium.org
BUG=libyuv:536, webrtc:5397, webrtc:5398, webrtc:5399

Review URL: https://codereview.chromium.org/1581123002 .